名称 : njsscan公司
在 :
推 :
分支 : [主人 ]
拉_请求 :
分支 : [主人 ]
工作 :
 njsscan公司 :
运行 :ubuntu最新
名称 : njsscan检查
步骤 :
 -名称 :检查代码
使用 :行动/签出@v2
 -名称 :节点jsscan扫描
身份证件 : njsscan公司
使用 : 阿吉纳布拉姆/ njsscan-action@主机
具有 :
 参数 : &#39;.&#39;
